config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :projects do
    resources :comments
  end
  
  root 'projects#index'
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :users
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :find_project, only: [:show,:edit,:update,:destroy]
  
  def index
    @projects=Project.all.order("created_at DESC")
  end
  
  def show
  end
  
  def new
    @project = Project.new
  end
  
  def create
    @project = Project.new(projects_params)
    
    if @project.save
      redirect_to @project
    else
      render "New"
    end
  end
  
  def edit
  end
  
  def update
    if @project.update(projects_params)
      redirect_to @project
    else
      render "edit"
    end
  end
  
  def destroy
    @project.destroy
    redirect_to root_path
  end
  
  private
  
  def projects_params
    params.require(:project).permit(:title, :client, :executor, :manager, :start_date, :end_date, :priority)
  end
  
  def find_project
    @project = Project.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:show,:edit,:update,:destroy]
  
  def index
    @users=User.all.order("created_at DESC")
  end
  
  def show
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(users_params)
    
    if @user.save
      redirect_to @user
    else
      render "New"
    end
  end
  
  def edit
  end
  
  def update
    if @user.update(users_params)
      redirect_to @user
    else
      render "edit"
    end
  end
  
  def destroy
    @user.destroy
    redirect_to root_path
  end
  
  private
  
  def users_params
    params.require(:user).permit(:name, :surname, :position, :email)
  end
  
  def find_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html
%head
	%title Ruby on Rails Jobs
	= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
	= javascript_include_tag 'application', 'data-turbolinks-track' => true
	= csrf_meta_tags

%body
	%nav.navbar.navbar-default
		.container
			.navbar-brand Project Board
			%ul.nav.navbar-nav
				%li= link_to "All Projects", root_path
				%li= link_to "All Users", users_path
			
					
			= link_to "New Project", new_project_path, class: "navbar-text navbar-right navbar-link"
			= link_to "New User", new_user_path, class: "navbar-text navbar-right navbar-link"
	.container
		.col-md-6.col-md-offset-3
			= yield

app/views/projects/_form.html.haml
= simple_form_for(@project, html: { class: 'form-horizontal'}) do |f|
	= f.input :title, label: "Project Title"
	= f.input :client, label: "Client Company"
	= f.input :executor, label: "Executor Company"
	= f.input :manager, label: "Project Manager"
	= f.input :start_date, label: "Start Date"
	= f.input :end_date, label: "End Date"
	= f.input :priority, label: "Priority", collection: 0..10
	%br/
	= f.button :submit

app/views/projects/edit.html.haml
%h1 Edit Project

= render 'form'

= link_to "Back", root_path

app/views/projects/index.html.haml
#projects
	- @projects.each do |project|
		.project
			%h2= link_to project.title, project
			%p= project.client
	
	

app/views/projects/new.html.haml
%h1 New Project

= render 'form'

= link_to "Back", root_path

app/views/projects/show.html.haml
#projects
	%h2= @project.title
	%p= @project.client
	%p= @project.executor
	%p= @project.manager
	%p= @project.start_date
	%p= @project.end_date
	%p= @project.priority
	
#links
	= link_to "Back", root_path, class: "btn btn-sm btn-default"
	= link_to "Edit", edit_project_path(@project), class: "btn btn-sm btn-default"
	= link_to "Delete", project_path(@project), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-sm btn-default"

app/views/users/_form.html.haml
= simple_form_for(@user, html: { class: 'form-horizontal'}) do |f|
	= f.input :name, label: "Name"
	= f.input :surname, label: "Surname"
	= f.input :position, label: "Position/Job Title"
	= f.input :email, label: "Email"
	%br/
	= f.button :submit

app/views/users/edit.html.haml
%h1 Edit User

= render 'form'

= link_to "Back", root_path

app/views/users/index.html.haml
#users
	- @users.each do |user|
		.user
			%h2= link_to user.name, user
			%p= user.position
= link_to "New user", new_user_path
	
	

app/views/users/new.html.haml
%h1 New User

= render 'form'

= link_to "Back", root_path

app/views/users/show.html.haml
#users
	.user
		%h2= @user.name
		%p= @user.surname
		%p= @user.position
		%p= @user.email
		
#links
	= link_to "Back", root_path, class: "btn btn-sm btn-default"
	= link_to "Edit", edit_user_path(@user), class: "btn btn-sm btn-default"
	= link_to "Delete", user_path(@user), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-sm btn-default"